events/urls.py
from .views import calendar_view, EventDateView, UserEventListView, all_tag,tagged_events,toggle_attending, LikeEventView, get_event, recently_posted_events,home, search,eventlist,categorylist,categoryview,citylist,cityview,create_event,upcoming_events,event_review_detail,event_review_list,create_event_review,trending_events,most_viewed
from django.urls import path

app_name='events'

urlpatterns=[
    path('events/search/', search, name='search'),
    path('events/event/<event_id>', get_event,name='event'),
    path('events/event_list',eventlist, name='home'),
    path('events/category_list <str:slug>/', categorylist, name='categorylist'),
    path('events/category_view/',categoryview, name='category'),
    path('events/city_view/',cityview, name='city'),
    path('events/city_list <str:slug>/',citylist, name='citylist'),
    path('events/new/', create_event,name='create_event'),
    path('events/upcoming_events/', upcoming_events, name='upcoming_events'),
    path('reviews/', event_review_list, name='event_review_list'),
    path('<int:event_id>/reviews/create/', create_event_review, name='create_event_review'),
    path('<int:event_id>/reviews/<int:review_id>/', event_review_detail, name='event_review_detail'),
    path('', home, name='home'),
    path('events/recently_posted/', recently_posted_events, name='recently_posted'),
    path('events/most_viewed/', most_viewed, name='most_viewed'),
    path('events/trending_events/', trending_events ,name='trending_events'),
    path('events/event/<int:event_id>/', LikeEventView.as_view(), name='like_event'),
    path('events/toggle_attending/<int:event_id>/', toggle_attending, name='toggle_attending'),
    path('events/tags/', all_tag, name='all_tags'),
    path('events/tags/<slug:slug>/', tagged_events, name='tagged_events'),
    path('events/user/<str:username>',UserEventListView.as_view(template_name='events/user_events.html'),name='user_events'),
    path('events/date/<int:year>/<int:month>/<int:day>/', EventDateView.as_view(), name='event_date'),
    path('events/calendar/', calendar_view, name='calendar'),
    #path('events/user_events',user_events,name='user_events')
]

kevent/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 
from profiles.views import register,profile,CustomLoginView
from django.contrib.auth import views as auth_views
from.views import about,contact


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    path('', include('newsletter.urls')),
    path('profile/', profile, name='profile'),
    path('register', register, name='register'),
    #path('login/', CustomLoginView.as_view(template_name='profiles/login.html'), name='login'),
    path('login', auth_views.LoginView.as_view (template_name='profiles/login.html'),name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='profiles/logout.html'),name='logout'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='profiles/password_reset.html'), name='password_reset'),
    path('about/',about,name='about'),
    path('contact/',contact,name='contact'),
    path('',include('comment.urls'))
 ]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/forms.py
from django import forms
from.models import Event,EventReview,Comment
from bootstrap_datepicker_plus.widgets import DatePickerInput,TimePickerInput
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.utils import timezone



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']  # Assuming your Comment model has a 'text' field for the actual comment text
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Add a comment...'}),
        }

class LikeForm(forms.Form):
    event_id = forms.IntegerField(widget=forms.HiddenInput())




class EventReviewForm(forms.ModelForm):
    class Meta:
        model=EventReview
        fields=['ratings', 'comment']
       



class EVentUploadForm(forms.ModelForm):
    class Meta:
        model=Event
        fields=['title', 'category','city','description','event_venue','entry_fee', 'event_date', 'event_time', 'thumb','tags' ]
        widgets={'event_date': DatePickerInput(),
                 'event_time':TimePickerInput(),
                 'description': forms.Textarea(attrs={'rows': 5, 'cols': 40}),}


        def __init__(self, *args, **kwargs):
            super(EVentUploadForm, self).__init__(*args, **kwargs)
            self.helper = FormHelper()
            self.helper.layout = Layout(
                'title',
                'city',
                'category',
                'description',
                'event_date',
                'event_time',
                'thumb',
                'event_venue',
            Submit('submit', 'Create Event')
            )


class EventSearchForm(forms.Form):
    title=forms.CharField(max_length=100, required=False, label='Search for events')

class CitySearchForm(forms.Form):
    city=forms.CharField(max_length=100, required=False, label='Search for the city')

events/views.py
from django.shortcuts import render, get_object_or_404, redirect 
from .models import Event, Category,City,EventReview
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from .forms import EventSearchForm
from viewanalytics.models import Analytics
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from .forms import EVentUploadForm,EventReviewForm,CommentForm
import random
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import datetime, timedelta
import datetime as time
from django.http import HttpResponseBadRequest,JsonResponse
from django.urls import reverse
from django.views.generic import ListView
from django.db.models import F, ExpressionWrapper, fields
from django.db.models.functions import Extract
from comment.models import Comment
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from taggit.models import Tag
from django.utils.decorators import method_decorator
from schedule.models import Calendar, Event as SchedulerEvent



class EventDateView(ListView):
    model = Event
    template_name = 'events/event_date.html'  # Create this template
    context_object_name = 'events'

    def get_queryset(self):
        year = self.kwargs['year']
        month = self.kwargs['month']
        day = self.kwargs['day']
        date = f'{year}-{month:02d}-{day:02d}'  # Format the date
        return Event.objects.filter(event_date=date)





class UserEventListView(ListView):
    model= Event
    template_name='events/user_events.html'
    context_object_name='events'

    def get_quaryset(self):
        user= get_object_or_404(User,username=self.kwargs.get('username'))
        return Event.objects.filter(uploaded_by=user).order_by('-upload_date')




def all_tag(request):
    tags=Tag.objects.all()
    return render(request, 'events/tags.html', {'tags':tags})



def tagged_events(request,slug):
    tag=get_object_or_404(Tag,slug=slug)
    events=Event.objects.filter(tags__in=[tag])
    context={
        'tag': tag,
        'events':events
    }
    return render(request,'events/tagged_events.html',context)



def paginate_events(request, events, page_size):
    paginator = Paginator(events, page_size)
    page = request.GET.get('page')

    try:
        paginated_events = paginator.page(page)
    except PageNotAnInteger:
        # If the page is not an integer, deliver the first page.
        paginated_events = paginator.page(1)
    except EmptyPage:
        # If the page is out of range, deliver the last page of results.
        paginated_events = paginator.page(paginator.num_pages)

    return paginated_events

def paginate_categories(request, category, page_size):
    paginator = Paginator(category, page_size)
    page = request.GET.get('page')

    try:
        paginated_category = paginator.page(page)
    except PageNotAnInteger:
        # If the page is not an integer, deliver the first page.
        paginated_category= paginator.page(1)
    except EmptyPage:
        # If the page is out of range, deliver the last page of results.
        paginated_category = paginator.page(paginator.num_pages)

    return paginated_category

def paginate_all_tags(request, all_tags, page_size):
    paginator = Paginator(all_tags, page_size)
    page = request.GET.get('page')

    try:
        paginated_all_tags = paginator.page(page)
    except PageNotAnInteger:
        # If the page is not an integer, deliver the first page.
        paginated_all_tags= paginator.page(1)
    except EmptyPage:
        # If the page is out of range, deliver the last page of results.
        paginated_all_tags = paginator.page(paginator.num_pages)

    return paginated_all_tags

def categorylist(request, slug):
    template='events/category_list.html'
    if (Category.objects.filter(slug=slug, status=0)):
        events=Event.objects.filter(category__slug=slug)
        category=Category.objects.filter(slug=slug).first()
        context={'events':events, 'category':category}

        events_per_page=20
        paginator=Paginator(events, events_per_page)
        page=request.GET.get('page')
        try:
            events=paginator.page('page')
        except PageNotAnInteger:
            events=paginator.page(1)
        except EmptyPage:
            events=paginator.page(paginator.num_pages)
        return render(request, template,context)


def home(request):
    #decay=0.05
    template='events/home.html'
    trending_events = Event.objects.annotate(
        age_in_days=ExpressionWrapper(
            Extract(F('upload_date'), 'day', output_field=fields.IntegerField()) +
            Extract(F('upload_date'), 'month', output_field=fields.IntegerField()) * 30 +
            Extract(F('upload_date'), 'year', output_field=fields.IntegerField()) * 365,
            output_field=fields.IntegerField()
        )
    ).annotate(
        weighted_score=ExpressionWrapper(
            F('views') + F('likes') + F('attending')* 2,  # Adjust weights as needed
            output_field=fields.IntegerField()
        ) * (1 / (1 + 0.05 * F('age_in_days')))
    ).order_by('-weighted_score')

    most_viewed=Event.objects.all().order_by('-views')
    recently_posted_events = Event.objects.all().order_by('-upload_date')
    upcoming_events=Event.objects.all().order_by('event_date')
    category=Category.objects.all().order_by('name')
    city=City.objects.all().order_by('name')
    tags=Tag.objects.all().order_by('name')
    
    paginated_trending_events=paginate_events(request,trending_events,page_size=12)
    paginated_most_viewed=paginate_events(request,most_viewed,page_size=12)
    paginated_recently_posted_events=paginate_events(request,recently_posted_events,page_size=12)
    paginated_upcoming_events=paginate_events(request,upcoming_events,page_size=9)
    paginated_categories=paginate_categories(request,category,page_size=6)
    paginated_tags=paginate_all_tags(request,tags,page_size=6)

    context={
        'most_viewed':paginated_most_viewed,
        'trending_events':paginated_trending_events,
        'recently_posted_events':paginated_recently_posted_events,
        'upcoming_events':paginated_upcoming_events,
        'categories':paginated_categories,
        'city':city,
        'tags':paginated_tags

    }

  

    return render(request,template,context)



def recently_posted_events(request):
    recently_posted_events = Event.objects.all().order_by('-upload_date')
    paginated_recently_posted_events=paginate_events(request,recently_posted_events,page_size=18)
    context={
        'recently_posted_events':paginated_recently_posted_events
    }
   
    return render(request, 'events/recently_posted_events.html', context)



def trending_events(request):
    trending_events = Event.objects.annotate(
        age_in_days=ExpressionWrapper(
            Extract(F('upload_date'), 'day', output_field=fields.IntegerField()) +
            Extract(F('upload_date'), 'month', output_field=fields.IntegerField()) * 30 +
            Extract(F('upload_date'), 'year', output_field=fields.IntegerField()) * 365,
            output_field=fields.IntegerField()
        )
    ).annotate(
        weighted_score=ExpressionWrapper(
            F('views') + F('likes') + F('attending') * 2,  # Adjust weights as needed
            output_field=fields.IntegerField()
        ) * (1 / (1 + 0.05 * F('age_in_days'))) #decay factor=0.05
    ).order_by('-weighted_score')
    paginated_trending_events=paginate_events(request,trending_events,page_size=18)
    context={
        'trending_events':paginated_trending_events
    }
    return render(request,'events/trending_events.html',context)






      
def most_viewed(request):
     most_viewed=Event.objects.all().order_by('-views')
     paginated_most_viewed=paginate_events(request,most_viewed,page_size=9)
     context={
          'most_viewed':paginated_most_viewed
     }
     return render(request,'events/most_viewed.html',context)




def event_review_detail(request, event_id, review_id):
    review=get_object_or_404(EventReview, id=review_id, event__id=event_id)
    return render(request, 'events/event_review_detail.html', {'review':review})




def event_review_list(request):
    reviews=EventReview.objects.all()
    context={'reviews': reviews}
    return render(request, 'events/event_review_list.html',context )





def create_event_review(request, event_id):
    event= get_object_or_404(Event, id=event_id)
    if request.method=="POST":
        form=EventReviewForm(request.POST)
        if form.is_valid():
            review=form.save(commit=False)
            review.user=request.user
            review.event=event
            review.event()
            return redirect('event_review_list', event_id=event.id)
    else:
        form=EventReviewForm()
    return render(request, 'events/create_event_review.html',{'event':event, 'form':form})




def eventlist(request):
    events=Event.objects.all()
    events_per_page=20
    paginator= Paginator(events,events_per_page)

    page=request.GET.get('page')

    try:
        events=paginator.page(page)
    except PageNotAnInteger:
        events=paginator.page(1)
    except EmptyPage:
        events=paginator.page(paginator.num_pages)
    return render(request,'events/event_list.html', {'events': events})





def search(request):
    events=[]
    query=''
    if 'title' in request.GET:
        form=EventSearchForm(request.GET)
        if form.is_valid():
            query=form.cleaned_data['title']
            events=Event.objects.filter(title__icontains=query)
    else:
        form=EventSearchForm()
    return render(request, 'events/search.html', {'form':form, 'events':events})






def categoryview(request):
    template='events/category.html'
    category=Category.objects.filter(status=0).order_by('name')
    context={'category':category}
    category_with_count=category.annotate(event_count=Count('event'))

events/templates/events/category_list.html
{% extends 'base.html'%}
{%load static%}
{% block title %}
{{category.name}}
{% endblock %}


{%block content%}
<section>

</section>
<section>
    <div class="container">
        <div class="section-header">
            <h4> {{category.name}} Events</h4>
        </div>
        <div class="row">
            {%if events%}
            {% for item in events %}
            <div class="col-lg-3">
                <div class="post-entry-1 lg">
                    <a href="{% url 'events:event' item.id  %}"> <img src="{{item.portrait.url}}" alt=""
                            class="img-fluid"></a>
                    <div class="post-meta"><span class="date"> {{item.category}}</span><span class="mx-1">
                            &bullet;</span><span> {{item.event_date}}</span>
                    </div>
                    <h2> <a href="{% url 'events:event' item.id  %}"> {{item.title}}</a></h2>
                    <div class="d-flex align-items-center author">
                        <div class="photo">
                            <a href="{% url 'events:user_events' item.uploaded_by.username %}"> <img src="{{ item.uploaded_by.profile.image.url }}" alt="" class="img-fluid"></a>
                        </div>
                        <div class="name">
                            <h3 class="m-0 p-0"> <a href="{% url 'events:user_events' item.uploaded_by.username %}">{{item.uploaded_by}} </a></h3>
                        </div>

                    </div>

                </div>

            </div>
            {%endfor%}
            {%else%}
            <div class="container-fluid">
                <div class="d-flex">
                    <p> Unfortunately there are no events in this city, be the the first one to <a
                            href="{% url 'events:create_event' %}"> <strong> add an event</strong> </a>
                        {%endif%}
                </div>
            </div>
</section>
{% endblock %}

events/templates/events/city_list.html
{% extends 'base.html'%}
{%load static%}
{% block title %}
{{city.name}}
{% endblock %}


{%block content%}
<section>
    
</section>
<section>
    <div class="container">
        <div class="section-header d-flex justify-content-between align-items-center mb-5">
            <h4> Events in {{city.name}}</h4>
            <div>
            <a href="/"> <i class="bi bi-houses-fill"></i></a>
            </div>
        </div>
        <div class="row">
            {%if events%}
            {% for item in events %}
            <div class="col-lg-3">
                <div class="post-entry-1 lg">
                    <a href="{% url 'events:event' item.id  %}"> <img src="{{item.portrait.url}}" alt=""
                            class="img-fluid"></a>
                    <div class="post-meta"><span class="date"> {{item.category}}</span><span class="mx-1">
                            &bullet;</span><span> {{item.event_date}}</span>
                    </div>
                    <h2> <a href="{% url 'events:event' item.id  %}"> {{item.title}}</a></h2>
                    <div class="d-flex align-items-center author">
                        <div class="photo">
                            <a href="{% url 'events:user_events' item.uploaded_by.username %}"> <img src="{{ item.uploaded_by.profile.image.url }}" alt="" class="img-fluid"></a>
                        </div>
                        <div class="name">
                            <h3 class="m-0 p-0"> <a href="{% url 'events:user_events' item.uploaded_by.username %}">{{item.uploaded_by}} </a></h3>
                        </div>

                    </div>

                </div>

            </div>
            {%endfor%}
            {%else%}
            <div class="container-fluid">
        <div class="d-flex">
            <p > Unfortunately there are no events in this city, be the the first one to <a
                     href="{% url 'events:create_event' %}"> <strong> add an event</strong> </a>
            {%endif%}
        </div>
    </div>
</section>
{% endblock %}

events/templates/events/event_review_detail.html
{% extends 'base.html'%}
{%load static%}
{% block title %}
Event Review Details
{% endblock %}


{%block content%}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <h1>{{ review.user.username }}'s Review for {{ review.event.title }}</h1>
                <p>Rating: {{ review.rating }}</p>
                <p>Comment: {{ review.comment }}</p>

            </div>
        </div>
    </div>
</section>

{% endblock %}

events/templates/events/most_viewed.html
{% extends 'base.html'%}
{%load static%}

{% block title %}
Most Viewed Events
{% endblock %}
{%block content%}
<section></section>
<section>
    <div class="container">
        <div class="section-header d-flex justify-content-between align-items-center mb-5">
            <h4>Most Viewed Events</h4>
            <div>
                <a href="/"> <i class="bi bi-houses-fill"></i></a>
            </div>
        </div>
        <div class="row">
            {%if most_viewed%}
            {% for item in most_viewed %}
            <div class="col-lg-3">
                <div class="post-entry-1 lg">
                    <a href="{% url 'events:event' item.id  %}"> <img src="{{item.portrait.url}}" alt=""
                            class="img-fluid"></a>
                    <div class="post-meta"><span class="date"> <a
                                href="{% url 'events:categorylist' item.category.slug %}">
                                {{item.category}}</a></span><span class="mx-1"> &bullet;</span><span><a
                                href="{% url 'events:citylist' item.city.slug%}">{{item.city}}</a></span><span>
                            <br>{{item.event_date}} </span>
                    </div>
                    <h2> <a href="{% url 'events:event' item.id  %}"> {{item.title}}</a></h2>
                    <div class="d-flex align-items-center author">
                        <div class="photo">
                            <a href="{% url 'events:user_events' item.uploaded_by.username %}"> <img src="{{ item.uploaded_by.profile.image.url }}" alt=""
                                    class="img-fluid"></a>
                        </div>
                        <div class="name">
                            <a href="">
                                <h3 class="m-0 p-0"> <a href="{% url 'events:user_events' item.uploaded_by.username %}">{{item.uploaded_by}} </a></h3>
                            </a>
                        </div>

                    </div>

                </div>

            </div>
            {%endfor%}
            {%else%}
            <p> No events available</p>
            {%endif%}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if most_viewed.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ most_viewed.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ most_viewed.number }} of {{ most_viewed.paginator.num_pages }}.
                </span>

                {% if most_viewed.has_next %}
                <a href="?page={{ most_viewed.next_page_number }}">next</a>
                <a href="?page={{ most_viewed.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</section>
{% endblock %}

events/templates/events/recently_posted_events.html
{% extends 'base.html'%}
{%load static%}

{% block title %}
Recently Posted  Events
{% endblock %}
{%block content%}
<section>

</section>

<section>
    <div class="container">
        <div class="section-header d-flex justify-content-between align-items-center mb-5">
            <h4>Recently Posted Events</h4>
            <div>
                <a href="/"> <i class="bi bi-houses-fill"></i></a>
            </div>
        </div>
        <div class="row">
            {%if recently_posted_events%}
            {% for item in recently_posted_events %}
            <div class="col-lg-3">
                <div class="post-entry-1 lg">
                    <a href="{% url 'events:event' item.id  %}"> <img src="{{item.portrait.url}}" alt=""
                            class="img-fluid"></a>
                    <div class="post-meta"><span class="date"> <a
                                href="{% url 'events:categorylist' item.category.slug %}">
                                {{item.category}}</a></span><span class="mx-1"> &bullet;</span><span><a
                                href="{% url 'events:citylist' item.city.slug%}">{{item.city}}</a></span><span>
                            <br>{{item.event_date}} </span>
                    </div>
                    <h2> <a href="{% url 'events:event' item.id  %}"> {{item.title}}</a></h2>
                    <div class="d-flex align-items-center author">
                        <div class="photo">
                            <a href="{% url 'events:user_events' item.uploaded_by.username %}"> <img src="{{ item.uploaded_by.profile.image.url }}" alt=""
                                    class="img-fluid"></a>
                        </div>
                        <div class="name">
                            <a href="">
                                <h3 class="m-0 p-0"> <a href="{% url 'events:user_events' item.uploaded_by.username %}">{{item.uploaded_by}} </a></h3>
                            </a>
                        </div>

                    </div>

                </div>

            </div>
            {%endfor%}
            {%else%}
            <p> No events available</p>
            {%endif%}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if recently_posted_events.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ recently_posted_events.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ recently_posted_events.number }} of {{ recently_posted_events.paginator.num_pages }}.
                </span>

                {% if recently_posted_events.has_next %}
                <a href="?page={{ recently_posted_events.next_page_number }}">next</a>
                <a href="?page={{recently_posted_events.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</section>
{% endblock %}

events/templates/events/tagged_events.html
{% extends 'base.html'%}
{%load static%}

{% block title %}
{{tag.name}}
{% endblock %}
{%block content%}
<section></section>

<section>
    <div class="container">
        <div class="section-header d-flex justify-content-between align-items-center mb-5">
            <h4>{{tag.name}}</h4>
            <div>
                <a href="/"> <i class="bi bi-houses-fill"></i></a>
            </div>
        </div>
        <div class="row">
            {%if events%}
            {% for item in events %}
            <div class="col-lg-3">
                <div class="post-entry-1 lg">
                    <a href="{% url 'events:event' item.id  %}"> <img src="{{item.portrait.url}}" alt=""
                            class="img-fluid"></a>
                    <div class="post-meta"><span class="date"> <a
                                href="{% url 'events:categorylist' item.category.slug %}">
                                {{item.category}}</a></span><span class="mx-1"> &bullet;</span><span><a
                                href="{% url 'events:citylist' item.city.slug%}">{{item.city}}</a></span><span>
                            <br>{{item.event_date}} </span>
                    </div>
                    <h2> <a href="{% url 'events:event' item.id  %}"> {{item.title}}</a></h2>
                    <div class="d-flex align-items-center author">
                        <div class="photo">
                            <a href="{% url 'events:user_events' item.uploaded_by.username %}"> <img src="{{ item.uploaded_by.profile.image.url }}" alt=""
                                    class="img-fluid"></a>
                        </div>
                        <div class="name">
                            <a href="">
                                <h3 class="m-0 p-0"> <a href="{% url 'events:user_events' item.uploaded_by.username %}">{{item.uploaded_by}} </a></h3>
                            </a>
                        </div>

                    </div>

                </div>

            </div>
            {%endfor%}
            {%else%}
            <p> No events available</p>
            {%endif%}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if events.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ events.previous_page_number }}">previous</a>
                {% endif %}


                {% if events.has_next %}
                <a href="?page={{ events.next_page_number }}">next</a>
                <a href="?page={{ events.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</section>

{%endblock%}

events/templates/events/trending_events.html
{% extends 'base.html'%}
{%load static%}

{% block title %}
Trending Events
{% endblock %}
{%block content%}
<section>

</section>
    <section>
        <div class="container">
            <div class="section-header d-flex justify-content-between align-items-center mb-5">
                <h4>Trending Events</h4>
                <div>
                    <a href="/"> <i class="bi bi-houses-fill"></i></a>
                </div>
            </div>
            <div class="row">
                {%if trending_events%}
                {% for item in trending_events %}
                <div class="col-lg-3">
                    <div class="post-entry-1 lg">
                        <a href="{% url 'events:event' item.id  %}"> <img src="{{item.portrait.url}}" alt=""
                                class="img-fluid"></a>
                        <div class="post-meta"><span class="date"> <a
                                    href="{% url 'events:categorylist' item.category.slug %}">
                                    {{item.category}}</a></span><span class="mx-1"> &bullet;</span><span><a
                                    href="{% url 'events:citylist' item.city.slug%}">{{item.city}}</a></span><span>
                                <br>{{item.event_date}} </span>
                        </div>
                        <h2> <a href="{% url 'events:event' item.id  %}"> {{item.title}}</a></h2>
                        <div class="d-flex align-items-center author">
                            <div class="photo">
                                <a href="{% url 'events:user_events' item.uploaded_by.username %}"> <img src="{{ item.uploaded_by.profile.image.url }}" alt=""
                                        class="img-fluid"></a>
                            </div>
                            <div class="name">
                                <a href="">
                                    <h3 class="m-0 p-0"> <a href="{% url 'events:user_events' item.uploaded_by.username %}">{{item.uploaded_by}} </a></h3>
                                </a>
                            </div>
    
                        </div>
    
                    </div>
    
                </div>
                {%endfor%}
                {%else%}
                <p> No events available</p>
                {%endif%}
            </div>
            <div class="pagination">
                <span class="step-links">
                    {% if trending_events.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ trending_events.previous_page_number }}">previous</a>
                    {% endif %}
    
                    <span class="current">
                        Page {{ trending_events.number }} of {{ trending_events.paginator.num_pages }}.
                    </span>
    
                    {% if trending_events.has_next %}
                    <a href="?page={{ trending_events.next_page_number }}">next</a>
                    <a href="?page={{ trending_events.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </section>
    {% endblock %}