events/urls.py
from .views import calendar_view, EventDateView, UserEventListView, all_tag,tagged_events,toggle_attending, LikeEventView, get_event, recently_posted_events,home, search,eventlist,categorylist,categoryview,citylist,cityview,create_event,upcoming_events,event_review_detail,event_review_list,create_event_review,trending_events,most_viewed
from django.urls import path

app_name='events'

urlpatterns=[
    path('events/search/', search, name='search'),
    path('events/event/<event_id>', get_event,name='event'),
    path('events/event_list',eventlist, name='home'),
    path('events/category_list <str:slug>/', categorylist, name='categorylist'),
    path('events/category_view/',categoryview, name='category'),
    path('events/city_view/',cityview, name='city'),
    path('events/city_list <str:slug>/',citylist, name='citylist'),
    path('events/new/', create_event,name='create_event'),
    path('events/upcoming_events/', upcoming_events, name='upcoming_events'),
    path('reviews/', event_review_list, name='event_review_list'),
    path('<int:event_id>/reviews/create/', create_event_review, name='create_event_review'),
    path('<int:event_id>/reviews/<int:review_id>/', event_review_detail, name='event_review_detail'),
    path('', home, name='home'),
    path('events/recently_posted/', recently_posted_events, name='recently_posted'),
    path('events/most_viewed/', most_viewed, name='most_viewed'),
    path('events/trending_events/', trending_events ,name='trending_events'),
    path('events/event/<int:event_id>/', LikeEventView.as_view(), name='like_event'),
    path('events/toggle_attending/<int:event_id>/', toggle_attending, name='toggle_attending'),
    path('events/tags/', all_tag, name='all_tags'),
    path('events/tags/<slug:slug>/', tagged_events, name='tagged_events'),
    path('events/user/<str:username>',UserEventListView.as_view(template_name='events/user_events.html'),name='user_events'),
    path('events/date/<int:year>/<int:month>/<int:day>/', EventDateView.as_view(), name='event_date'),
    path('events/calendar/', calendar_view, name='calendar'),
    #path('events/user_events',user_events,name='user_events')
]

kevent/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 
from profiles.views import register,profile,CustomLoginView
from django.contrib.auth import views as auth_views
from.views import about,contact


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    path('', include('newsletter.urls')),
    path('profile/', profile, name='profile'),
    path('register', register, name='register'),
    #path('login/', CustomLoginView.as_view(template_name='profiles/login.html'), name='login'),
    path('login', auth_views.LoginView.as_view (template_name='profiles/login.html'),name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='profiles/logout.html'),name='logout'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='profiles/password_reset.html'), name='password_reset'),
    path('about/',about,name='about'),
    path('contact/',contact,name='contact'),
    path('',include('comment.urls'))
 ]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from .views import subscribe, subscribe_success, newsletter_list
app_name='newsletter'
urlpatterns = [
    path('newsletter/subscribe/', subscribe, name='subscribe'),
    path('newsletter/subscribe_success/', subscribe_success, name='subscribe_success'),
    path('newsletter/newsletter_list/', newsletter_list, name='newsletter_list'),
]

templates/about.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
About
{% endblock %}

{% block content%}
<section></section>

    <section>
        <div class="container" data-aos="fade-up">
            <div class="row">
                <div class="col-lg-12 text-center mb-5">
                    <h1 class="page-title">About us</h1>
                </div>
            </div>
    
            <div class="row mb-5">
    
                <div class="d-md-flex post-entry-2 half">
                    <a href="#" class="me-4 thumbnail">
                        <img src="assets/img/post-landscape-2.jpg" alt="" class="img-fluid">
                    </a>
                    <div class="ps-md-5 mt-4 mt-md-0">
                        <div class="post-meta mt-4">About us</div>
                        <h2 class="mb-4 display-4">Company History</h2>
    
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime,
                            adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident
                            inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam
                            temporibus aut!</p>
                        <p>Fugit eaque illum blanditiis, quo exercitationem maiores autem laudantium unde excepturi dolores
                            quasi eos vero harum ipsa quam laborum illo aut facere voluptates aliquam adipisci sapiente
                            beatae ullam. Tempora culpa iusto illum accusantium cum hic quisquam dolor placeat officiis
                            eligendi.</p>
                    </div>
                </div>
    
                <div class="d-md-flex post-entry-2 half mt-5">
                    <a href="#" class="me-4 thumbnail order-2">
                        <img src="assets/img/post-landscape-1.jpg" alt="" class="img-fluid">
                    </a>
                    <div class="pe-md-5 mt-4 mt-md-0">
                        <div class="post-meta mt-4">Mission &amp; Vision</div>
                        <h2 class="mb-4 display-4">Mission &amp; Vision</h2>
    
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime,
                            adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident
                            inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam
                            temporibus aut!</p>
                        <p>Fugit eaque illum blanditiis, quo exercitationem maiores autem laudantium unde excepturi dolores
                            quasi eos vero harum ipsa quam laborum illo aut facere voluptates aliquam adipisci sapiente
                            beatae ullam. Tempora culpa iusto illum accusantium cum hic quisquam dolor placeat officiis
                            eligendi.</p>
                    </div>
                </div>
    
            </div>
    
        </div>
    </section>
{% endblock %}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title> 
        {% block title %}
    
        {% endblock %}
    </title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
   

    <!-- Template Main CSS Files -->
    <link href="{% static 'assets/css/variables.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
    <!-- Add these links in the head section of your HTML -->


    <style>
        section {
        max-width: 70%;
        margin: 20px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

    button {
        background-color: rgb(6, 6, 6);
        color: white;
        padding: 10px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #2a2424;
    }
    </style>

  
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

            <a href="/" class="logo d-flex align-items-center">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="assets/img/logo.png" alt=""> -->
                <h1 style="color: white;">EventNews</h1>
            </a>

            <nav id="navbar" class="navbar"  >
                <ul style="color: white;">
                    <li>
                        <a href=" /">Home</a>
                    </li>
                    <li style="color: white;" class="{% if request.path == '/events:create_event' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'events:create_event' %}">Post Event</a>
                    </li>
                    <li class="dropdown" style="color: white;"><a href="#"><span>Events Central</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            <li><a href="{% url 'events:upcoming_events' %}">Upcoming Events</a></li>
                            <li><a href="{% url 'events:recently_posted' %}">Recently Posted Events </a></li>
                            <li><a href="{% url 'events:trending_events' %}">Trending Events</a></li>
                            <li><a href="{% url 'events:most_viewed' %}">Most Viewed Events</a></li>
                            <li><a href="{% url 'events:calendar' %}">Event Calendar</a></li>
                        </ul>
                    </li>
                </li>
                <li  style="color: white;"class="{% if request.path == '/event_review_list/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'events:event_review_list' %}">Event Review</a>
                </li>
                <li style="color: white;" class="{% if request.path == '/category/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'events:category' %}">Categories</a>
                </li>
                <li style="color: white;" class="{% if request.path == '/city/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'events:city' %}">Cities</a>
                </li>
                <li style="color: white;" class="{% if request.path == '/city/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'events:all_tags' %}">Tags</a>
                </li>
                </ul>
            </nav><!-- .navbar -->

            <div class="position-relative">
                <a href="#" class="mx-2"><span class="bi-facebook"></span></a>
                <a href="#" class="mx-2"><span class="bi-twitter"></span></a>
                <a href="#" class="mx-2"><span class="bi-instagram"></span></a>
                <a href="{% url 'events:search' %}" class="mx-2 js-search-open"><span class="bi-search"></span></a>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </div>
            {% if user.is_authenticated %}
            <div class=" position-relative">
                <form method="" action="{% url 'profile' %}">
                    {% csrf_token %}
                    <button style="background-color: grey;color:white;" type="submit">{{ user.username}}</button>
                </form>
            </div>
            <div class="position-relative">
             <form method="post" action="{% url 'logout' %}">
                {% csrf_token %} <button style="background-color: grey;color:white;" type="submit">Logout</button></form></a>
            </div>
            {% else %}
            <div  class=" position-relative">
                <form method="" action="{% url 'login' %}?next={{ request.GET.next }}">
                    {% csrf_token %}
                    <button  style="background-color: white; color: grey;" type="submit">Login</button>
                </form>
            </div>
            <div class="position-relative">
                <form method="" action="{% url 'register' %}">
                    {% csrf_token %} <button  style="background-color: white; color: gray;" type="submit">Register</button></form></a>
            </div>
            {% endif %}

        </div>

    </header><!-- End Header -->
    


{% block content %}

{% endblock %}
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
    
        <div class="footer-content">
            <div class="container">
    
                <div class="row g-5">
                    <div class="col-lg-3">
                        <h3 class="footer-heading">EventNews</h3>
                        <p><a href="/about" class="footer-link-more">Learn More</a></p>
                    </div>
                        <div class=" col-lg-3">
                            <h3 class="footer-heading">Legal and company</h3>
                            <ul class="footer-links list-unstyled">
                                <li><a href="#"><i class="bi bi-chevron-right"></i> Disclaimer</a></li>
                                <li><a href="#"><i class="bi bi-chevron-right"></i> Terms of use</a></li>
                                <li><a href="#"><i class="bi bi-chevron-right"></i>Privacy policy</a></li>
                                <li><a href="#"><i class="bi bi-chevron-right"></i> Sponsored events</a></li>
                                <li><a href="{% url 'contact' %}"><i class="bi bi-chevron-right"></i> Contact</a></li>
                        
                            </ul>
                        </div>
                    <div class="col-lg-3">
                        <h3 class="footer-heading">Navigation</h3>
                        <ul class="footer-links list-unstyled">
                            <li><a href="/"><i class="bi bi-chevron-right"></i> Events Central</a></li>
                            <li><a href="{% url 'events:event_review_list' %}"><i class="bi bi-chevron-right"></i> Event Reviews</a></li>
                            <li><a href="{% url 'events:category' %}"><i class="bi bi-chevron-right"></i>Events By Category</a></li>
                            <li><a href="{% url 'events:city' %}"><i class="bi bi-chevron-right"></i> Events By City</a></li>
                           

                        </ul>
                    </div>
             
                    
                    <div class="col-lg-3">
                        <h3 class="footer-heading">Subscribe to newsletter</h3>
                    
                        <ul class="footer-links footer-blog-entry list-unstyled">
                            <li>
                                <a href="{% url 'newsletter:subscribe' %}" class="d-flex align-items-center"> Subscribe
                                    
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    
                    
    
        <div class="footer-legal">
            <div class="container">
    
                <div class="row justify-content-between">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        <div class="copyright">
                            © Copyright <strong><span>EventNews</span></strong>. All Rights Reserved
                        </div>
    
                    </div>
    
                    <div class="col-md-6">
                        <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
                            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="bi bi-skype"></i></a>
                            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                        </div>
    
                    </div>
    
                </div>
    
            </div>
        </div>
    
    </footer>
    
    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    
    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    
    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
<script>
    document.querySelectorAll(".nav-link").forEach((link) => {
        if (link.href === window.location.href) {
            link.classList.add("active");
            link.setAttribute("aria-current", "page");
        }
    });
</script>

    
    </body>
    
    </html>

templates/contact.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Contact
{% endblock %}

{% block content%}
<section></section>
<section id="contact" class="contact mb-5">
    <div class="container" data-aos="fade-up">

        <div class="row">
            <div class="col-lg-12 text-center mb-5">
                <h1 class="page-title">Contact us</h1>
            </div>
        </div>

        <div class="row gy-4">

            <div class="col-md-4">
                <div class="info-item">
                    <i class="bi bi-geo-alt"></i>
                    <h3>Address</h3>
                    <address>A108 Adam Street, NY 535022, USA</address>
                </div>
            </div><!-- End Info Item -->

            <div class="col-md-4">
                <div class="info-item info-item-borders">
                    <i class="bi bi-phone"></i>
                    <h3>Phone Number</h3>
                    <p><a href="tel:+155895548855">+1 5589 55488 55</a></p>
                </div>
            </div><!-- End Info Item -->

            <div class="col-md-4">
                <div class="info-item">
                    <i class="bi bi-envelope"></i>
                    <h3>Email</h3>
                    <p><a href="mailto:info@example.com">info@example.com</a></p>
                </div>
            </div><!-- End Info Item -->

        </div>

        <div class="form mt-5">
            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                <div class="row">
                    <div class="form-group col-md-6">
                        <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                    </div>
                    <div class="form-group col-md-6">
                        <input type="email" class="form-control" name="email" id="email" placeholder="Your Email"
                            required>
                    </div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
                </div>
                <div class="form-group">
                    <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
                </div>
                <div class="my-3">
                    <div class="loading">Loading</div>
                    <div class="error-message"></div>
                    <div class="sent-message">Your message has been sent. Thank you!</div>
                </div>
                <div class="text-center"><button type="submit">Send Message</button></div>
            </form>
        </div><!-- End Contact Form -->

    </div>
</section>
{% endblock %}